# This simply tells Istio about our JWT and where to find the JWKS. "authn"
apiVersion: security.istio.io/v1
kind: RequestAuthentication
metadata:
  name: "jwt-example"
  namespace: backend
spec:
  selector:
    matchLabels:
      app: httpbin
  jwtRules:
  - issuer: "vault-demo"
    jwksUri: "http://jwks.vault.svc.cluster.local:8080/.well-known/jwks.json"
    outputPayloadToHeader: "x-jwt-payload"
---
# This is what actually tells Istio that things must pass the JWT validation to be passed. "authz"
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: require-jwt
  namespace: backend
spec:
  selector:
    matchLabels:
      app: httpbin
  action: ALLOW
  rules:
  - from: 
    - source: 
       requestPrincipals: ["vault-demo/demo-user"] # iss/sub of the jwt payload
    when:
      - key: request.auth.claims[is_admin]
        values: ["True"]