apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: base
    namespace: istio-system
    repo: https://istio-release.storage.googleapis.com/charts
    version: "1.26.2"
  - name: istiod
    namespace: istio-system
    repo: https://istio-release.storage.googleapis.com/charts
    version: "1.26.2"
